language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - git clone https://github.com/libssh2/libssh2.git && cd libssh2 && autoconf && ./configure && make && make install
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - yes "" | pecl install -f ssh2-beta
  - phpenv config-rm xdebug.ini
  - composer self-update && composer install --dev --prefer-source --no-interaction

script:
  - php bin/phpspec run -fpretty --verbose
  - php bin/phpunit
